version: '3.3'

services:
  inbox:
    build: services/inbox
    environment:
      - MONGODB_URI=mongodb://mongodb
    depends_on:
      -mongodb
    restart: "unless-stopped"
  mongodb:
    image: mongo:3.4
    volumes:
      -mongo-data:/data/db
    restart: "unless-stopped"
  webserver:
    build: services/webserver
    environment:
      - MONGODB_URI=mongodb://mongodb
    depends_on:
      -mongodb
    restart: "unless-stopped"

volumes:
  mongo-data:
