version: '3.3'

services:
  gateway:
    ports:
      - "8080:80"
    image: httpd
    restart: unless-stopped
    volumes:
      - ./services/gateway/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

  inbox:
    build: services/inbox
    environment:
      - EUCO_MAIL_SERVER_HOST=${EUCO_MAIL_SERVER_HOST}
      - EUCO_MAIL_SERVER_PORT=${EUCO_MAIL_SERVER_PORT}
      - EUCO_MAIL_USER=${EUCO_MAIL_USER}
      - EUCO_MAIL_PWD=${EUCO_MAIL_PWD}
    depends_on:
      - mongodb
    restart: "unless-stopped"

  playmaker:
    build: services/playmaker
    depends_on:
      - mongodb
    restart: "unless-stopped"

  mongodb:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    restart: "unless-stopped"

  api:
    build: services/api
    depends_on:
      - mongodb
    restart: "unless-stopped"

  ui:
    build: services/ui
    restart: "unless-stopped"

volumes:
  mongo-data:
