version: '3.3'

services:
  inbox:
    build: services/inbox
    environment:
      - MONGODB_URI=mongodb://mongodb
      - EUCO_MAIL_SERVER_HOST=${EUCO_MAIL_SERVER_HOST}
      - EUCO_MAIL_SERVER_PORT=${EUCO_MAIL_SERVER_PORT}
      - EUCO_MAIL_USER=${EUCO_MAIL_USER}
      - EUCO_MAIL_PWD=${EUCO_MAIL_PWD}
    depends_on:
      -mongodb
    restart: "unless-stopped"
  mongodb:
    image: mongo:3.4
    volumes:
      -mongo-data:/data/db
    restart: "unless-stopped"
  webserver:
    build: services/webserver
    depends_on:
      -mongodb
    restart: "unless-stopped"

volumes:
  mongo-data:
